### ISSUE TITLE
Couldn't find preset "airbnb"

### ISSUE THREAD

**Issue by anhtuank7c** [lelandrichardson/redux-pack#46] opened 2017-03-16 05:12 UTC
I don't use `babel-preset-airbnb` in my current project.

Seem your dependencies `deline` required `airbnb` preset.
Hum...
I got this error.
![screen shot 2017-03-16 at 12 00 12 pm](https://cloud.githubusercontent.com/assets/3163410/23982604/18c6bb54-0a41-11e7-8624-cfc2c3afdb02.png)

I don't know where should i raise issue (this one or deline one)?

I resolve this issue by:
- yarn add --dev babel-preset-airbnb (or npm install --save-dev babel-preset-airbnb)
- add `airbnb` to presets array in `.babelrc`

**Comment by lelandrichardson** [comment] 2017-03-25 20:10
Hmm. Is there a reason you're compiling your node_modules? Is this a react-native project?

**Comment by aforty** [comment] 2017-04-05 14:48
That looks like a react-native style error message. I think they take a different approach and compile themselves when possible.

**Comment by anhtuank7c** [comment] 2017-04-06 07:28
@lelandrichardson @aforty 
I do run in project root folder.

**Comment by willdavidow** [comment] 2017-04-08 11:56
So, I had a similar error, except it was on the `react-native` package (I'm not building a react-native app):

```
ERROR in ../~/redux-pack/lib/index.js
Module build failed: Error: Couldn't find preset "react-native" relative to directory "/Users/me/site/node_modules/redux-pack"
    at /Users/me/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/me/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/me/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/me/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/me/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/me/site/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/me/site/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/me/site/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/me/site/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/me/site/node_modules/babel-loader/lib/index.js:163:20)
 @ ./app.js 19:17-38
```

Fixed by installing installing `babel-preset-react-native`

Now I'm on this issue and fixed it by installing and enabled `babel-preset-airbnb` and that fixed all the compile issues I was having.

I'm guessing issue is being caused by `.babelrc` - https://github.com/lelandrichardson/redux-pack/blob/master/.babelrc

**Comment by bohrend** [comment] 2017-10-17 12:19
Hi, just thought I would share, i tried all of the above still didnt work, after which I did a `react-native link` and it worked.  (btw awesome library thank you!)

**Comment by benbender** [comment] 2017-10-17 13:48
The right solution is to exclude node_modules in babel-loader (or whatever you use).
Example for webpack:

```
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
```

**Comment by nickcobbett** [comment] 2017-12-14 00:59
I had the same issue in a create-react-native app. The solution was to change the .babelrc file in node_modules/deline as follows:
`{
  "presets": ["babel-preset-airbnb"]
}
`
then from the command line within that directory:  `npm run build`

**EDIT: I haven't checked, but it's possible that just running `npm run build`  from the deline/ directory without altering the .babelrc file will suffice**

**Comment by JasonTolliver** [comment] 2018-03-28 19:37
@nickcobbett I can confirm that simply running `npm run build` from the `deline` directory did the trick for me.

**Comment by no-stack-dub-sack** [comment] 2018-04-07 00:55
@lelandrichardson I ran into this same issue with a TypeScript project (where node_modules is being excluded from compilation), had to install both react-native and airbnb presets to get around this issue.

**Comment by nilscox** [comment] 2018-04-18 21:36
I also got this error with create-react-native-app, fixed by installing `babel-preset-airbnb`. Seems like a broken dependency.

**Comment by ljharb** [comment] 2018-04-18 22:35
This is a flaw inherent in the react-native packager. The solution (until they fix it themselves) is to, in your app, on postinstall, remove all `.babelrc` files inside `node_modules`, and hope and pray that none of your dependencies have transpilation settings that conflict with the RNP's.

**Comment by richardzyx** [comment] 2018-11-27 22:10
+1 for this issue on RN. Just ran into this after adding redux-pack to a working project.

**Comment by richardzyx** [comment] 2018-11-27 22:17
Confirm that installing `babel-preset-airbnb` v3.0.1 as a project dependency doesn't work. I'm on RN 0.55.4 and there's a version conflict with babel core.

> error: bundling failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

**Comment by ljharb** [comment] 2018-11-27 22:48
Closing; https://github.com/lelandrichardson/redux-pack/issues/46#issuecomment-382550471 is the solution.

**Comment by richardzyx** [comment] 2018-11-27 23:45
Hmm interesting, I tried it in several way, from postinstall to manually deleting all the files, and got the same error

> bundling failed: Error: Couldn't find preset "airbnb" relative to directory

**Comment by ljharb** [comment] 2018-11-27 23:47
@richardzyx if `.babelrc` is indeed deleted, then there's nothing that should be referencing `babel-preset-airbnb`.

**Closed** 2018-11-27 23:46 UTC

**Comment by richardzyx** [comment] 2018-11-28 20:03
@ljharb in the latest release, the .babelrc only contains preset react-native

```
{
  "presets": ["react-native"]
}
```

The only reference I could find for `airbnb` was in ESLint file, and deleting the line `"extends": "airbnb"` doesn't help although I'm trying to see if I can recompile all the modules.

**Comment by ljharb** [comment] 2018-11-28 20:03
@richardzyx sure, but eslint should only *ever* run on your first-party code, never on node_modules.

**Comment by richardzyx** [comment] 2018-11-28 20:07
@ljharb right, so the issue is redux-pack's `.babelrc` file has preset for react-native which caused it to try to find the airbnb preset?

**Comment by ljharb** [comment] 2018-11-28 20:09
i don't think so; the issue seems to be that your eslint is probably not ignoring node_modules - perhaps because you have a monorepo, and nested node_modules directories aren't ignored by default?

**Comment by richardzyx** [comment] 2018-11-28 20:17
Thanks for the suggestion. I've ran the installation again, made sure redux-pack babelrc file is deleted, and got the same error. I checked and react-native-ble-plx & react-native-vector-icons libraries have the same babel preset without causing issues, which should rule out nested node_modules possibility. And ESLint is configured to ignore node_modules.

**Comment by richardzyx** [comment] 2018-11-28 20:49
Actually, I was able to fix this issue by simply removing the .babelrc file from `deline`. I was removing babelrc from redux-pack but deline is the broken dependency that couldn't run on RN.

Resolved!

**Comment by richardzyx** [comment] 2018-11-28 20:49
So I suppose the suggestion is to take out or replace deline as a dependency to make redux-pack compatible with RN out of the box.

**Comment by ljharb** [comment] 2018-11-28 21:23
As https://github.com/lelandrichardson/redux-pack/issues/46#issuecomment-382550471 says, you'll need to recursively remove *all* `.babelrc` files inside node_modules, until RNP fixes their architecture flaw.

**Comment by richardzyx** [comment] 2018-11-28 21:27
@ljharb In my case it wasn't necessary as I kept all the other .babelrc files and only needed to delete the babel file from deline. I think you are right to suggest that as a general solution, and I'm unsure of the root cause.

**Comment by ljharb** [comment] 2018-11-28 21:32
The root cause is that the RNP incorrectly transpiles code inside node_modules, by design.
